### ISSUE TITLE
License appears to be incompatible with Python source from which it was derived

### ISSUE THREAD

**Issue by mr-c** [dropbox/typed_ast#12]
Please fix or clarify so I can package typed_ast for Debian. Thanks

**Comment by gvanrossum** [comment]
What kind of incompatibility are you concerned about? The LICENSE currently has both Apache 2.0 2.0 and MIT.

**Comment by mr-c** [comment]
Ah, I didn't see the additional contents and just presumed it was the Apache 2.0 license only. It is unclear as to which license applies to which code paths or even eras of contributions. Perhaps a couple sentences can be added to the top?

Bonus, you could adopt Debian's machine & human readable copyright & licensing format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

**Comment by gvanrossum** [comment]
Can you send us a PR for that?

**Comment by mr-c** [comment]
Sure. Also, the LICENSE file wasn't shipped in the sdist on PyPI which is what I based the packaging off of.

**Comment by gvanrossum** [comment]
OK, since you are the first person to care about this please help us fix it!

**Comment by mr-c** [comment]
Ready for your review: #13

**Comment by ddfisher** [comment]
Fixed by #13.
