### ISSUE TITLE
Does not compile under MSVC 14

### ISSUE THREAD

**Issue by oyarsa** [dropbox/typed_ast#20]
When I tried to install the package using pip, I received the following error: http://pastebin.com/fDNWdR7Z

Python 3.5.0
pip 8.1.2
Visual Studio 14 Update 3

**Comment by gvanrossum** [comment]
Thanks! This is actually a known issue that we're working on, but there was no issue for it yet. Now there is one.

**Comment by ddfisher** [comment]
It turns out there are actually a fair amount of compilation errors to work through after that one.  My work in progress is at https://github.com/ddfisher/typed_ast, but it still doesn't compile yet.

**Comment by ddfisher** [comment]
As of https://github.com/dropbox/typed_ast/commit/a3f63eb6b9e5db7cb4792830f6dfe84497ca4fcc, typed_ast should now compile and run on Windows for Python 3.5.  I've also put up Windows wheels on PyPI, so you shouldn't need to compile it yourself unless you want to develop on it.

Closing as fixed, but let us know if you run into any issues!
