### ISSUE TITLE
What's the point of inserting a space character in the dump before extra fields?

### ISSUE THREAD

**Issue by mbdevpl** [dropbox/typed_ast#23]
In `dump()` function, there's the following expression [in line 116](https://github.com/dropbox/typed_ast/blob/master/typed_ast/ast35.py#L116):

    rv += fields and ', ' or ' '

The space character literal at the end of the expression causes the dump of e.g. `Pass` to be:

    Pass( lineno=44, col_offset=4)

Is there a point to this? Or, could it be that this space should be removed, so that the dump is:

    Pass(lineno=44, col_offset=4)

?

I've done this in this commit, should I PR? https://github.com/mbdevpl/typed_ast/commit/589d064ff427b372c8550839719aa6fd21290e42

**Comment by ddfisher** [comment]
That's a good question, but you'll have to ask the CPython folks.  The `dump()` function in `ast27` and `ast35` is exactly the same as the version in the CPython `ast` library.  (See [here](https://github.com/python/cpython/blob/master/Lib/ast.py#L106).)  `typed_ast` is intended to behave as similarly as possible to `ast` (aside from type comment-related changes), so I don't want to change this behavior, even though I agree it's a little strange.
